config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  get 'opening/index'

  get 'contacts/index'

  resources "applications", only: [:new, :create]

end

app/models/application.rb
class Application < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :positionappliedfor
  attribute :telephone
  attribute :address
  attribute :postcode
  attribute :secondaryschool
  attribute :datestartandfinished
  attribute :examinationsandresults
  attribute :furtheredandtraining
  attribute :datestartandfinishedtwo
  attribute :coursesandqualifications
  attribute :employername
  attribute :employeraddress
  attribute :fromandto
  attribute :descriptionofrole
  attribute :reasonforleaving

  attribute :employernametwo
  attribute :employeraddresstwo
  attribute :fromandtotwo
  attribute :descriptionofroletwo
  attribute :reasonforleavingtwo

  attribute :employernamethree
  attribute :employeraddressthree
  attribute :fromandtothree
  attribute :descriptionofrolethree
  attribute :reasonforleavingthree

  attribute :referee1
  attribute :refereecontactnumber1
  attribute :refereecontactemail1
  attribute :referee2
  attribute :refereecontactnumber2
  attribute :refereecontactemail2


  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "mcgoveranmaloneroad@centra.co.uk",
      :from => %("Automated Service" <mcgoveranmaloneroad@centra.co.uk>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def new
    @application = Application.new
  end

  def create
    @application = Application.new(params[:application])
    @application.request = request
    if @application.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/opening_controller.rb
class OpeningController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opening_helper.rb
module OpeningHelper
end

app/helpers/recruitment_helper.rb
module RecruitmentHelper
end

app/views/applications/create.html.erb
<h1>Thank you for your application!</h1>

app/views/applications/new.html.erb
<div class="apply_form">
<%= image_tag "apply_header.png", :class => "img_header" %>


<%= simple_form_for @application, :html => {:class => 'form-horizontal' } do |f| %>
  <div class="field">
    <label>Position Applied For : </label>
    <%= f.input :positionappliedfor, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label><span class="redtxt">*</span> Full Name : </label>
    <%= f.input :name, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label>Contact Telephone Number : </label>
    <%= f.input :telephone, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label><span class="redtxt">*</span>Email Address : </label>
    <%= f.input :email, :required => false, :label => false %></br></br>
  </div>
  <div class="field_area">
    <label>Address : </label>
    <%= f.input :address, :required => false, :label => false, :as => :text, :class => "fieldarea" %></br>
  </div>
  <div class="field">
    <label>Postal Code : </label>
    <%= f.input :postcode, :required => false, :label => false %></br>
  </div>
  <%= image_tag "edu_header.png", :class => "img_header" %>
  <div class="field">
    <label>Secondary School Names : </label>
    <%= f.input :secondaryschool, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label>Dates Started and Finished : </label>
    <%= f.input :datestartandfinished, :required => false, :label => false %></br></br>
  </div>
  <div class="field_area">
    <label>Examinations and Results : </label>
    <%= f.input :examinationsandresults, :required => false, :label => false, :as => :text, :class => "fieldarea" %></br>
  </div>
  <div class="field">
    <label>Further Education and Training : </label>
    <%= f.input :furtheredandtraining, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label>Dates Started and Finished : </label>
    <%= f.input :datestartandfinishedtwo, :required => false, :label => false %></br></br>
  </div>
  <div class="field_area">
    <label>Courses and Qualifications : </label>
    <%= f.input :coursesandqualifications, :required => false, :label => false, :as => :text, :class => "fieldarea" %></br>
  </div>
  <%= image_tag "emp_header.png", :class => "img_header" %>
  <div class="field">
    <label>Employer Name : </label>
    <%= f.input :employername, :required => false, :label => false %></br></br>
  </div>
  <div class="field_area">
    <label>Employer Address : </label>
    <%= f.input :employeraddress, :required => false, :label => false, :as => :text, :class => "fieldarea" %></br>
  </div>
  <div class="field">
    <label>From and To : </label>
    <%= f.input :fromandto, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label>Description of Role : </label>
    <%= f.input :descriptionofrole, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label>Reason For Leaving : </label>
    <%= f.input :reasonforleaving, :required => false, :label => false %></br>
  </div>
  <hr>
    <div class="field">
    <label>Employer Name : </label>
    <%= f.input :employernametwo, :required => false, :label => false %></br></br>
  </div>
  <div class="field_area">
    <label>Employer Address : </label>
    <%= f.input :employeraddresstwo, :required => false, :label => false, :as => :text, :class => "fieldarea" %></br>
  </div>
  <div class="field">
    <label>From and To : </label>
    <%= f.input :fromandtotwo, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label>Description of Role : </label>
    <%= f.input :descriptionofroletwo, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label>Reason For Leaving : </label>
    <%= f.input :reasonforleavingtwo, :required => false, :label => false %></br>
  </div>
  <hr>
  <div class="field">
    <label>Employer Name : </label>
    <%= f.input :employernamethree, :required => false, :label => false %></br></br>
  </div>
  <div class="field_area">
    <label>Employer Address : </label>
    <%= f.input :employeraddressthree, :required => false, :label => false, :as => :text, :class => "fieldarea" %></br>
  </div>
  <div class="field">
    <label>From and To : </label>
    <%= f.input :fromandtothree, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label>Description of Role : </label>
    <%= f.input :descriptionofrolethree, :required => false, :label => false %></br>
  </div>
  <div class="field">
    <label>Reason For Leaving : </label>
    <%= f.input :reasonforleavingthree, :required => false, :label => false %></br>
  </div>
  <%= image_tag "referral_header.png", :class => "img_header" %>
  <div class="field">
    <label>Referee Name : </label>
    <%= f.input :referee1, :required => false, :label => false %></br></br>
  </div>
  <div class="field">
    <label>Referee Contact Number : </label>
    <%= f.input :refereecontactnumber1, :required => false, :label => false %></br></br>
  </div>
  <div class="field">
    <label>Referee Contact Email : </label>
    <%= f.input :refereecontactemail1, :required => false, :label => false %></br></br>
  </div>
  <hr>
  <div class="field">
    <label>Referee Name #2 : </label>
    <%= f.input :referee2, :required => false, :label => false %></br></br>
  </div>
  <div class="field">
    <label>Referee Contact Number #2 : </label>
    <%= f.input :refereecontactnumber2, :required => false, :label => false %></br></br>
  </div>
  <div class="field">
    <label>Referee Contact Email #2 : </label>
    <%= f.input :refereecontactemail2, :required => false, :label => false %></br></br>
  </div>

  <%= f.button :submit, 'Apply now', :class=> "btn btn-primary marg_bottom submit" %>
<% end %>
</div>

app/views/contacts/index.html.erb
<div class="center_contact">
  <div class="contact_left">
    <b>Paul @ Stranmillis</b></br>
    </br>
    66/70 Stranmillis Road</br>
    Belfast</br>
</br>
    02890684740</br>
</br>
    mcgoveranstranmillis@centra.co.uk
  </div>
  <div class="contact_right">
    <b>Jamie @ Malone</b></br>
</br>
    42/46 Malone Road</br>
    Belfast</br>
</br>
    02890380111</br>
</br>
    mcgoveranmaloneroad@centra.co.uk
  </div>
</div>

app/views/home/index.html.erb
<!--<div class="mcgoveran_header">
  <%= image_tag "mcgoverans.png" %>
</div>-->

<div class="fb_con">
  <center>
  <%= image_tag "checkusout.png", :class => "cuo" %>
  </center>
  <center>
    <a href="https://www.facebook.com/centra.stranmillismalone" target=_blank>
    <%= image_tag "fb_logo.png" %>
    <span class="fbme">fb.me/centrastranmillismalone</span>
    </a>
  </center>
</div>

<div class="about">
  <div class="arrow">
    
  </div>
  <div class="text_sec">
    <!--<%= image_tag "recruit_img.png" %>-->
  </div>

  <div class="img_sec">
   <center><%= image_tag "centra1_alt.jpg", :class => "multi" %><%= image_tag "centra2_alt.jpg", :class => "multi" %><%= image_tag "centra3_alt.jpg", :class => "multi" %></center>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Centra</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="http://code.jquery.com/jquery-latest.min.js"
        type="text/javascript"></script>
  <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="header">
  <div class="inner_header">
    <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "new_logo.png" %>
    <% end %>
    <span id="menuOpen">&#9776;</span>
    </div>

    <div class="navbar">
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Recruitment", new_application_path %></li>
        <li><%= link_to "Contact", contacts_index_path %></li>
      </ul>
    </div>
  </div>
</div>
  <div class="mobile_links" id="menuList">
    <ul>
      <li class="exit_menu"><span id="menuClose">X</span></li>
      <li class="secli"><%= link_to "Home", root_path %></li>
      <li><%= link_to "Recruitment", new_application_path %></li>
      <li class="secli"><%= link_to "Contact", contacts_index_path %></li>
    </ul>
  </div>
<div class="container">

<%= yield %>

<span class="credits"><a href="http://coreypizzle.github.io">Designed by Corey Purdy</a></span>
</div>

<script type="text/javascript">
  $("#menuOpen").click(function(){
    $("#menuList").show()
  });
</script>

<script type="text/javascript">
  $("#menuClose").click(function(){
    $("#menuList").hide()
  });
</script>

</body>
</html>

app/views/opening/index.html.erb
<%= image_tag "opening_header.png" %>